In [1]:
import numpy as np

### 1. 

In [2]:
iris = np.genfromtxt(r"C:\Users\91852\Downloads\Iris_clean_-_Copy.csv", dtype = 'float16', delimiter = ',')

In [3]:
iris

array([[      nan,       nan,       nan,       nan],
       [5.102e+00, 3.500e+00, 1.400e+00, 2.000e-01],
       [4.898e+00, 3.000e+00, 1.400e+00, 2.000e-01],
       [4.699e+00, 3.199e+00, 1.300e+00, 2.000e-01],
       [4.602e+00, 3.100e+00, 1.500e+00, 1.020e+01],
       [5.000e+01, 3.600e+00, 1.400e+00, 2.000e-01],
       [5.398e+00,       nan, 1.700e+00, 3.999e-01],
       [4.602e+00, 3.400e+00, 1.400e+00, 3.000e-01],
       [5.000e+00, 3.400e+00, 1.500e+00, 2.000e-01],
       [4.398e+00, 2.900e+00, 1.400e+00, 2.000e-01],
       [4.898e+00, 3.100e+00,       nan, 9.998e-02],
       [5.398e+00, 3.699e+00, 1.500e+00, 2.000e-01],
       [4.801e+00, 3.400e+00, 1.600e+00, 2.000e-01],
       [4.801e+00, 1.300e+02, 1.400e+00, 1.010e+01],
       [4.301e+00, 3.000e+00, 1.100e+00, 9.998e-02],
       [5.801e+00, 4.000e+00, 1.200e+00, 2.000e-01],
       [5.699e+00, 4.398e+00, 1.500e+00, 3.999e-01],
       [5.041e+01,       nan, 1.300e+00, 3.999e-01],
       [5.102e+00, 3.500e+00, 1.400e+00, 3.000

In [4]:
slen = iris[1:,0]

In [5]:
swid = iris[1:,1]

In [6]:
plen = iris[1:,2]

In [7]:
pwid = iris[1:,3]

#### Replacing missing values

In [8]:
slen = np.where(np.isnan(slen), np.nanmedian(slen), slen)

In [9]:
swid = np.where(np.isnan(swid), np.nanmedian(swid), swid)

In [10]:
plen = np.where(np.isnan(plen), np.nanmedian(plen), plen)

In [11]:
pwid = np.where(np.isnan(pwid), np.nanmedian(pwid), pwid)

#### Outliers

In [12]:
q1slen = np.quantile(slen, 0.25)
q3slen = np.quantile(slen, 0.75)
iqrslen = q3slen - q1slen
iqrslen

1.30078125

In [13]:
llslen = q1slen - 1.5*iqrslen
ulslen = q3slen + 1.5*iqrslen

In [14]:
np.median(slen)

5.8

In [15]:
slen_o = (slen<llslen) | (slen>ulslen)
slen[slen_o]

array([ 50. ,  50.4, 116.3,  70.2], dtype=float16)

In [16]:
slen = np.where(slen_o, np.median(slen), slen)
slen

array([5.1, 4.9, 4.7, 4.6, 5.8, 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.8, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 5.8, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 5.8,
       5.8, 5.8, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9, 5.6, 7.7, 5.8, 5.8, 7.2, 4.9,
       7.3, 6.7, 5.9, 5.6, 7.7, 6.3, 7.2, 6.5, 6.4], dtype=float16)

In [17]:
slen_o = (slen<llslen) | (slen>ulslen)
slen[slen_o]

array([], dtype=float16)

In [18]:
q1swid = np.quantile(swid, 0.25)
q3swid = np.quantile(swid, 0.75)
iqrswid = q3swid - q1swid
iqrswid

0.5

In [19]:
llswid = q1swid - 1.5*iqrswid
ulswid = q3swid + 1.5*iqrswid

In [20]:
swid_o = (swid<llswid) | (swid>ulswid)
swid[swid_o]

array([130. ,   4.4,  34. ,   4.1,   4.2,   2. , 112.6], dtype=float16)

In [21]:
swid = np.where(swid_o, np.median(swid), swid)
swid

array([3.5, 3. , 3.2, 3.1, 3.6, 3. , 3.4, 3.4, 2.9, 3.1, 3.7, 3.4, 3. ,
       3. , 4. , 3. , 3. , 3.5, 3.8, 3.8, 3.4, 3.7, 3.6, 3.3, 3.4, 3. ,
       3. , 3.5, 3.4, 3.2, 3.1, 3.4, 3. , 3. , 3.1, 3.2, 3.5, 3.1, 3. ,
       3.4, 3.5, 2.3, 3.2, 3.5, 3.8, 3. , 3.8, 3.2, 3.7, 3.3, 3.2, 3.2,
       3. , 2.3, 2.8, 2.8, 3.3, 2.4, 2.9, 2.7, 3. , 3. , 2.2, 2.9, 2.9,
       3.1, 3. , 2.7, 2.2, 2.5, 3.2, 2.8, 2.5, 3. , 2.9, 3. , 2.8, 3. ,
       2.9, 2.6, 2.4, 2.4, 2.7, 2.7, 3. , 3.4, 3.1, 2.3, 3. , 2.5, 2.6,
       3. , 3. , 2.3, 2.7, 3. , 2.9, 2.9, 2.5, 2.8, 3.3, 2.7, 3. , 2.9,
       3. , 3. , 2.5, 2.9, 2.5, 3.6, 3.2, 2.7, 3. , 2.5, 2.8, 3.2, 3. ,
       3.8, 2.6, 2.2, 3.2, 2.8, 2.8, 2.7, 3.3, 3.2, 2.8, 3. , 2.8, 3. ,
       2.8, 3.8, 2.8, 2.8, 2.6, 3. , 3.4, 3. , 3. , 3.1, 3.1, 3.1, 2.7,
       3.2, 3.3, 3. , 2.5, 3. , 3.4, 3. , 2.8, 2.8, 2.7, 3.3, 3.2, 2.5,
       2.9, 2.5, 3. , 2.8, 2.8, 2.7, 3.6, 3.2, 2.7], dtype=float16)

In [22]:
swid_o = (swid<llswid) | (swid>ulswid)
swid[swid_o]

array([], dtype=float16)

In [23]:
q1plen = np.quantile(plen, 0.25)
q3plen = np.quantile(plen, 0.75)
iqrplen = q3plen - q1plen
iqrplen

3.501953125

In [24]:
llplen = q1plen - 1.5*iqrplen
ulplen = q3plen + 1.5*iqrplen

In [25]:
plen_o = (plen<llplen) | (plen>ulplen)
plen[plen_o]

array([13. , 13.8], dtype=float16)

In [26]:
plen = np.where(plen_o, np.median(plen),plen)
plen

array([1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, 4.5, 1.5, 1.6, 1.4,
       1.1, 1.2, 1.5, 1.3, 1.4, 1.7, 1.5, 1.7, 1.5, 1. , 1.7, 1.9, 1.6,
       1.6, 1.5, 1.4, 1.6, 1.6, 1.5, 1.5, 1.4, 1.5, 1.2, 1.3, 1.5, 1.3,
       1.5, 1.3, 4.5, 1.3, 1.6, 1.9, 1.4, 1.6, 1.4, 1.5, 1.4, 4.7, 4.5,
       4.9, 4. , 4.6, 4.5, 4.7, 3.3, 4.6, 3.9, 3.5, 4.2, 4. , 4.7, 3.6,
       4.4, 4.5, 4.1, 4.5, 3.9, 4.8, 4. , 4.9, 4.7, 4.3, 4.4, 4.8, 5. ,
       4.5, 3.5, 4.5, 3.7, 3.9, 5.1, 4.5, 4.5, 4.7, 4.4, 4.1, 4. , 4.4,
       4.5, 4. , 3.3, 4.2, 4.2, 4.2, 4.3, 3. , 4.1, 6. , 5.1, 5.9, 5.6,
       5.8, 6.6, 4.5, 6.3, 5.8, 6.1, 5.1, 5.3, 4.5, 5. , 5.1, 5.3, 5.5,
       6.7, 6.9, 5. , 5.7, 4.9, 6.7, 4.9, 5.7, 6. , 4.8, 4.9, 5.6, 5.8,
       6.1, 4.5, 5.6, 5.1, 5.6, 6.1, 5.6, 5.5, 4.8, 5.4, 4.5, 5.1, 5.1,
       5.9, 5.7, 4.5, 5. , 5.2, 5.4, 5.1, 4.9, 6.7, 4.9, 5.7, 6. , 4.5,
       6.3, 5.8, 5.1, 4.9, 6.7, 4.9, 6.1, 5.1, 5.3], dtype=float16)

In [27]:
plen_o = (plen<llplen) | (plen>ulplen)
plen[plen_o]

array([], dtype=float16)

In [28]:
q1pwid = np.nanquantile(pwid, 0.25)
q3pwid = np.nanquantile(pwid, 0.75)
iqrpwid = q3pwid - q1pwid
iqrpwid

1.50048828125

In [29]:
llpwid = q1pwid - 1.5*iqrpwid
ulpwid = q3pwid + 1.5*iqrpwid

In [30]:
pwid_o = (pwid<llpwid) | (pwid>ulpwid)
pwid[pwid_o]

array([ 10.2,  10.1, 110.2,  16. , 111.1], dtype=float16)

In [31]:
pwid = np.where(pwid_o, np.median(pwid), pwid)
pwid

array([0.2, 0.2, 0.2, 1.5, 0.2, 0.4, 0.3, 0.2, 0.2, 0.1, 0.2, 0.2, 1.5,
       0.1, 0.2, 0.4, 0.4, 0.3, 0.3, 0.3, 0.2, 0.4, 0.2, 0.5, 0.2, 0.2,
       0.4, 0.2, 1.5, 0.2, 0.2, 0.4, 0.1, 0.2, 0.1, 0.2, 0.2, 0.1, 0.2,
       0.2, 0.3, 0.3, 0.2, 0.6, 0.4, 0.3, 0.2, 0.2, 0.2, 0.2, 1.4, 1.5,
       1.5, 1.3, 1.5, 1.3, 1.6, 1.5, 1.3, 1.4, 1. , 1.5, 1. , 1.4, 1.3,
       1.4, 1.5, 1. , 1.5, 1.1, 1.8, 1.3, 1.5, 1.2, 1.3, 1.4, 1.4, 1.7,
       1.5, 1. , 1.1, 1. , 1.2, 1.6, 1.5, 1.6, 1.5, 1.3, 1.3, 1.3, 1.2,
       1.4, 1.2, 1. , 1.3, 1.2, 1.3, 1.3, 1.5, 1.3, 2.5, 1.9, 2.1, 1.8,
       2.2, 2.1, 1.7, 1.8, 1.8, 2.5, 2. , 1.9, 2.1, 2. , 2.4, 2.3, 1.8,
       2.2, 2.3, 1.5, 2.3, 2. , 2. , 1.8, 2.1, 1.8, 1.8, 1.8, 2.1, 1.6,
       1.9, 2. , 2.2, 1.5, 1.4, 2.3, 2.4, 1.8, 1.8, 2.1, 2.4, 2.3, 1.9,
       2.3, 2.5, 2.3, 1.9, 2. , 2.3, 1.8, 2. , 2. , 1.8, 2.1, 1.8, 1.7,
       1.8, 1.8, 1.8, 2. , 2. , 1.8, 2.5, 2. , 1.9], dtype=float16)

In [32]:
pwid_o = (pwid<llpwid) | (pwid>ulpwid)
pwid[pwid_o]

array([], dtype=float16)

### 2.

In [33]:
slen.mean()

5.87

### 3.

In [34]:
np.sort(swid)

array([2.2, 2.2, 2.2, 2.3, 2.3, 2.3, 2.3, 2.4, 2.4, 2.4, 2.5, 2.5, 2.5,
       2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.6, 2.6, 2.6, 2.6, 2.7, 2.7,
       2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.8, 2.8, 2.8,
       2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8,
       2.8, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9, 3. ,
       3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. ,
       3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. ,
       3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3.1, 3.1,
       3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.2, 3.2, 3.2, 3.2, 3.2,
       3.2, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2, 3.3, 3.3, 3.3,
       3.3, 3.3, 3.3, 3.3, 3.4, 3.4, 3.4, 3.4, 3.4, 3.4, 3.4, 3.4, 3.4,
       3.4, 3.4, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.6, 3.6, 3.6, 3.6, 3.7,
       3.7, 3.7, 3.8, 3.8, 3.8, 3.8, 3.8, 3.8, 4. ], dtype=float16)

### 4.

In [35]:
np.mean(slen)

5.87

In [36]:
np.median(slen)

5.8

In [37]:
np.var(slen)

0.6533

In [38]:
np.std(slen)

0.808

In [39]:
np.max(slen) - np.min(slen)

3.398

In [40]:
np.mean(swid)

3.014

In [41]:
np.median(swid)

3.0

In [42]:
np.var(swid)

0.135

In [43]:
np.std(swid)

0.3674

In [44]:
np.max(swid) - np.min(swid)

1.801

### 5.

In [45]:
data = np.array((slen,swid, plen, pwid))

In [46]:
np.savetxt('cleaned_iris.txt',data)

In [47]:
np.loadtxt('cleaned_iris.txt')

array([[5.1015625 , 4.8984375 , 4.69921875, 4.6015625 , 5.80078125,
        5.3984375 , 4.6015625 , 5.        , 4.3984375 , 4.8984375 ,
        5.3984375 , 4.80078125, 4.80078125, 4.30078125, 5.80078125,
        5.69921875, 5.80078125, 5.1015625 , 5.69921875, 5.1015625 ,
        5.3984375 , 5.1015625 , 4.6015625 , 5.1015625 , 4.80078125,
        5.        , 5.        , 5.19921875, 5.19921875, 4.69921875,
        4.80078125, 5.3984375 , 5.19921875, 5.5       , 4.8984375 ,
        5.        , 5.5       , 4.8984375 , 4.3984375 , 5.1015625 ,
        5.        , 4.5       , 4.3984375 , 5.        , 5.1015625 ,
        4.80078125, 5.1015625 , 4.6015625 , 5.30078125, 5.        ,
        7.        , 6.3984375 , 6.8984375 , 5.5       , 6.5       ,
        5.69921875, 5.80078125, 4.8984375 , 6.6015625 , 5.19921875,
        5.        , 5.8984375 , 6.        , 6.1015625 , 5.6015625 ,
        6.69921875, 5.6015625 , 5.80078125, 6.19921875, 5.6015625 ,
        5.8984375 , 6.1015625 , 6.30078125, 6.10