In [1]:
import numpy as np

### Creation of ndarray

#### 1.

In [3]:
a1 = np.arange(10, 81, 5)

In [18]:
a1.reshape((1,5,3))

array([[[10, 15, 20],
        [25, 30, 35],
        [40, 45, 50],
        [55, 60, 65],
        [70, 75, 80]]])

In [74]:
a2 = np.array([10,12,14,16,18,20,25,30,35,40,50,60,70,80,90], ndmin = 3)

In [6]:
a2

array([[[10, 12, 14, 16, 18, 20, 25, 30, 35, 40, 50, 60, 70, 80, 90]]])

In [7]:
a2.ndim

3

In [11]:
a3 = np.array([[[2,4,6,8,10,12,14,16,18,20,22,24,26,28,30]]])

In [12]:
a3.ndim

3

#### 2.

In [125]:
arr1 = np.arange(1,13).reshape((1,2,3,2))

In [126]:
arr1

array([[[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],

        [[ 7,  8],
         [ 9, 10],
         [11, 12]]]])

In [127]:
arr1.ndim

4

In [128]:
array1 = np.linspace(0, 1.3 , num =20).reshape((2,5,2))

In [129]:
print(array1)
array1.ndim

[[[0.         0.06842105]
  [0.13684211 0.20526316]
  [0.27368421 0.34210526]
  [0.41052632 0.47894737]
  [0.54736842 0.61578947]]

 [[0.68421053 0.75263158]
  [0.82105263 0.88947368]
  [0.95789474 1.02631579]
  [1.09473684 1.16315789]
  [1.23157895 1.3       ]]]


3

#### 3. attributes

In [130]:
arr1.size

12

In [131]:
arr1.itemsize

4

In [132]:
arr1.nbytes

48

In [133]:
arr1.dtype

dtype('int32')

In [134]:
arr1.shape

(1, 2, 3, 2)

In [135]:
arr1.ndim

4

In [136]:
array1.size

20

In [137]:
array1.itemsize

8

In [138]:
array1.nbytes

160

In [139]:
array1.dtype

dtype('float64')

In [140]:
array1.ndim

3

In [141]:
array1.shape

(2, 5, 2)

#### 4.

In [142]:
arr1.mean()

6.5

In [143]:
np.median(arr1)

6.5

In [144]:
range1 = arr1.max() - arr1.min()
print(range1)


11


In [145]:
arr1.var()

11.916666666666666

In [146]:
arr1.std()

3.452052529534663

In [147]:
q1 = np.percentile(arr1, 25)
q1

3.75

In [148]:
q3 = np.percentile(arr1, 75)
q3

9.25

In [149]:
iqr = q3 - q1
iqr

5.5

In [150]:
ll = q1-1.5*iqr
ll

-4.5

In [151]:
ul = q3 + 1.5*iqr
ul

17.5

In [152]:
arr1[arr1<ll]

array([], dtype=int32)

In [153]:
arr1[arr1>ul]

array([], dtype=int32)

#### 4b. array1 stats

In [154]:
array1.mean()

0.6500000000000001

In [155]:
np.median(array1)

0.65

In [156]:
np.var(array1)

0.1556578947368421

In [157]:
np.std(array1)

0.39453503613347457

In [158]:
range2 = np.max(array1) - array1.min()
print(range2)

1.3


In [159]:
q1 = np.percentile(array1, 25)
q1

0.325

In [160]:
q3 = np.percentile(array1, 50)
q3

0.65

In [161]:
iqr = q3 - q1
iqr

0.325

In [162]:
ll = q1 - 1.5*iqr
ll

-0.16250000000000003

In [166]:
ul = q3 + 1.5*iqr
ul

1.1375000000000002

In [167]:
array1[array1<ll]

array([], dtype=float64)

In [168]:
array1[array1>ul]

array([1.16315789, 1.23157895, 1.3       ])

### Array Slicing and Indexing

In [170]:
arr1 = np.array([0, 11, 26, 73, 42, 51, 6,77, 8,29])
arr1

array([ 0, 11, 26, 73, 42, 51,  6, 77,  8, 29])

In [172]:
arr2 = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [174]:
arr1[2]

26

In [176]:
arr2[1][0]

3

In [177]:
arr1[:5]

array([ 0, 11, 26, 73, 42])

In [183]:
arr2[1:,:2]

array([[3, 4],
       [6, 7]])

In [185]:
arr1[1:7:2]

array([11, 73, 51])

### Data Type Manipulation

In [187]:
arr1 = np.array([1,2,3,4,5], dtype = 'int16')

In [188]:
arr1.dtype

dtype('int16')

In [189]:
arr2 = np.array([0.1, 0.2, 0.3, 0.4, 0.5])

In [190]:
arr2.dtype

dtype('float64')

In [194]:
a = np.array(arr2, dtype = 'int32')
a

array([0, 0, 0, 0, 0])

In [195]:
a.dtype

dtype('int32')

In [196]:
b = np.array(arr1, dtype = 'float32')
b

array([1., 2., 3., 4., 5.], dtype=float32)

### Generating Random Numbers

In [197]:
random = np.random.randint(0,100,10)

In [198]:
random

array([34, 98, 44, 79, 76, 76, 72, 48, 85, 79])

In [199]:
uni = np.random.uniform(-1,1, 5)

In [200]:
uni

array([-0.2389221 ,  0.76503934,  0.78107206, -0.17681209, -0.07179754])

In [203]:
m = np.random.randint(50,100,16).reshape((4,4))

In [204]:
m

array([[80, 76, 73, 73],
       [70, 95, 67, 82],
       [50, 66, 72, 60],
       [93, 98, 58, 89]])

In [205]:
m.ndim

2

In [206]:
np.mean(m)

75.125

In [207]:
np.median(m)

73.0

In [208]:
mrange = np.max(m) - np.min(m)
mrange

48

In [209]:
np.var(m)

178.109375

In [210]:
np.std(m)

13.34576243606936

In [211]:
q1 = np.percentile(m, 25)
q1

66.75

In [212]:
q3 = np.percentile(m, 75)
q3

83.75

In [213]:
iqr = q3 -q1
iqr

17.0

In [214]:
ll = q1 - 1.5*iqr
ll

41.25

In [215]:
ul = q3 + 1.5*iqr
ul

109.25

In [216]:
m[m<ll]

array([], dtype=int32)

In [217]:
m[m>ul]

array([], dtype=int32)

### Analyze the Data:

In [218]:
Salaries = [87877, 54494, 54804, 85051, 52453, 31250, 94868, 66349, 39828, 60501, 58570, 74906, 41671, 51428, 56414, 98446, 56819, 82833, 50477, 62898, 99658, 89224, 34225, 79172, 32199, 63795, 90947, 55723, 64557, 3113638]

In [219]:
sal = np.array(Salaries)

In [220]:
sal

array([  87877,   54494,   54804,   85051,   52453,   31250,   94868,
         66349,   39828,   60501,   58570,   74906,   41671,   51428,
         56414,   98446,   56819,   82833,   50477,   62898,   99658,
         89224,   34225,   79172,   32199,   63795,   90947,   55723,
         64557, 3113638])

In [223]:
print('more than 50000:')
len(sal[sal>50000])

more than 50000:


25

In [225]:
print('less than 50000:')
len(sal[sal<50000])

less than 50000:


5

In [231]:
mean = sal.mean()
mean

166169.16666666666

In [232]:
std = sal.std()
std

547678.585700353

In [246]:
pstd1 = mean + std
pstd1

713847.7523670197

In [247]:
mstd1 = mean - std
mstd1

-381509.4190336864

In [251]:
sal[sal<pstd1]

array([87877, 54494, 54804, 85051, 52453, 31250, 94868, 66349, 39828,
       60501, 58570, 74906, 41671, 51428, 56414, 98446, 56819, 82833,
       50477, 62898, 99658, 89224, 34225, 79172, 32199, 63795, 90947,
       55723, 64557])

In [249]:
sal[sal>mstd1]

array([  87877,   54494,   54804,   85051,   52453,   31250,   94868,
         66349,   39828,   60501,   58570,   74906,   41671,   51428,
         56414,   98446,   56819,   82833,   50477,   62898,   99658,
         89224,   34225,   79172,   32199,   63795,   90947,   55723,
         64557, 3113638])

In [256]:
len(sal[sal>mstd1])

30

In [257]:
np.mean(sal)

166169.16666666666

In [258]:
np.median(sal)

61699.5

In [259]:
rangesal = np.max(sal) - np.min(sal)
rangesal

3082388

In [270]:
q3 = np.percentile(sal, 75)
a=sal[sal>sal.mean()]
b=sal[sal<=q3]
np.intersect1d(a,b)

array([], dtype=int32)

In [272]:
q1 = np.percentile(sal,25)
len(sal[sal<q1])

8