In [1]:
import numpy as np

### 1. 

In [7]:
a1 = np.zeros(10, dtype = 'int8')
a1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [10]:
a2 = np.ones(7)
a2

array([1., 1., 1., 1., 1., 1., 1.])

In [11]:
lst = [1,2,3,4,5]
a3 = np.array(lst)
a3

array([1, 2, 3, 4, 5])

In [12]:
tup = (6,7,8,9,10)
a4 = np.array(tup)
a4

array([ 6,  7,  8,  9, 10])

In [15]:
a5 = np.array([10, 20, 30])
a5

array([10, 20, 30])

In [18]:
a6 = np.linspace(1,5, 20)
a6

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [22]:
a7 = np.arange(10, 50, 5)
a7

array([10, 15, 20, 25, 30, 35, 40, 45])

### 2.

In [23]:
arr1 = np.arange(1,13)

In [24]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [25]:
array1 = np.linspace(0, 12, 20)

In [26]:
array1

array([ 0.        ,  0.63157895,  1.26315789,  1.89473684,  2.52631579,
        3.15789474,  3.78947368,  4.42105263,  5.05263158,  5.68421053,
        6.31578947,  6.94736842,  7.57894737,  8.21052632,  8.84210526,
        9.47368421, 10.10526316, 10.73684211, 11.36842105, 12.        ])

### 3. Attributes

In [27]:
arr1.dtype

dtype('int32')

In [28]:
arr1.itemsize

4

In [29]:
arr1.size

12

In [30]:
arr1.nbytes

48

In [31]:
arr1.ndim

1

In [51]:
array1.dtype

dtype('float64')

In [52]:
array1.itemsize

8

In [53]:
array1.size

20

In [54]:
array1.nbytes

160

In [55]:
array1.ndim

1

### 4. 

#### Mean

In [56]:
np.mean(arr1)

6.5

In [67]:
np.mean(array1)

5.999999999999999

#### Median

In [65]:
np.median(arr1)

6.5

In [68]:
np.median(array1)

6.0

#### Variance

In [57]:
arr1.var()

11.916666666666666

In [69]:
np.var(array1)

13.26315789473684

#### Std Deviation

In [58]:
arr1.std()

3.452052529534663

In [70]:
np.std(array1)

3.6418618720013036

#### Range

In [59]:
arr1.min()

1

In [60]:
arr1.max()

12

In [61]:
range_arr1 = arr1.max() - arr1.min()
print(range_arr1)

11


In [71]:
range_array1 = array1.max() - array1.min()
print(range_array1)

12.0


#### IQR

In [62]:
q1 = np.percentile(arr1, 25)

In [63]:
q3 = np.percentile(arr1, 75)

In [72]:
iqr = q3 - q1
print('arr1 IQR= ',iqr)

arr1 IQR=  5.5


In [74]:
q1_a2=np.percentile(array1, 25)
q3_a2=np.percentile(array1, 75)
iqr_array1 = q3_a2 - q1_a2
print('array1 IQR = ', iqr_array1)

array1 IQR =  6.0


#### Outliers

In [75]:
LLa1 = q1 - 1.5*iqr
ULa1 = q3 + 1.5*iqr
print(f'Lower limit is {LLa1} and upper limit is {ULa1}')

Lower limit is -4.5 and upper limit is 17.5


In [77]:
arr1[arr1>ULa1]

array([], dtype=int32)

In [79]:
arr1[arr1<LLa1]

array([], dtype=int32)

In [78]:
#no outliers

In [81]:
LLa2 = q1_a2 - 1.5*iqr_array1
ULa2 = q3_a2 + 1.5*iqr_array1
print(f'Lower limit is {LLa2} and upper limit is {ULa2}')

Lower limit is -6.0 and upper limit is 18.0


In [83]:
array1[array1<LLa2]

array([], dtype=float64)

In [84]:
array1[array1>ULa2]

array([], dtype=float64)

In [ ]:
#no outliers