In [1]:
import numpy as np

### Data Cleaning using numpy

In [9]:
marks = np.array([44,24,np.nan,59,32,96,188,52,62,58,52,120,np.nan,np.nan,3,56,81,59,122,92,np.nan,87,96,97,1,19,2,53, 44])
marks

array([ 44.,  24.,  nan,  59.,  32.,  96., 188.,  52.,  62.,  58.,  52.,
       120.,  nan,  nan,   3.,  56.,  81.,  59., 122.,  92.,  nan,  87.,
        96.,  97.,   1.,  19.,   2.,  53.,  44.])

#### 1.

In [13]:
np.sum((marks<0) | (marks>100))

3

There are three outliers

In [16]:
np.sum(np.isnan(marks))

4

There are 4 missing values

#### 2.

In [20]:
marks = np.where((marks<0) | (marks>100),45,marks)
marks

array([44., 24., nan, 59., 32., 96., 45., 52., 62., 58., 52., 45., nan,
       nan,  3., 56., 81., 59., 45., 92., nan, 87., 96., 97.,  1., 19.,
        2., 53., 44.])

In [21]:
mks = np.where(np.isnan(marks),87, marks).astype('int16')
mks

array([44, 24, 87, 59, 32, 96, 45, 52, 62, 58, 52, 45, 87, 87,  3, 56, 81,
       59, 45, 92, 87, 87, 96, 97,  1, 19,  2, 53, 44], dtype=int16)

In [23]:
print('Avg marks of the class = ', np.mean(mks))

Avg marks of the class =  56.96551724137931


In [31]:
print('num of students who scored less than 60:', sum(mks<60))

num of students who scored less than 60: 18


In [32]:
print('max marks obtained= ',np.max(mks))

max marks obtained=  97


In [33]:
mks.astype('float32')

array([44., 24., 87., 59., 32., 96., 45., 52., 62., 58., 52., 45., 87.,
       87.,  3., 56., 81., 59., 45., 92., 87., 87., 96., 97.,  1., 19.,
        2., 53., 44.], dtype=float32)

### Solving Linear Equations

In [34]:
a = np.array([[2,3,-1],[1,-1,2],[3,2,1]])
b= np.array([10,5,12])

In [40]:
np.linalg.solve(a,b)

array([-6.75539944e+15,  6.75539944e+15,  6.75539944e+15])

In [35]:
x,y,z=np.linalg.solve(a,b)

In [36]:
x

-6755399441055741.0

In [37]:
y

6755399441055745.0

In [38]:
z

6755399441055744.0

In [39]:
a2 = np.array([[2,1,-1,3],[3,-2,2,2],[1,3,-2,1],[4,-1,1,-2]])
b2 = np.array([8,1,7,3])

In [41]:
x,y,z,w = np.linalg.solve(a2,b2)

In [42]:
x

1.731707317073171

In [43]:
y

-0.7560975609756105

In [44]:
z

-3.4634146341463428

In [45]:
w

0.6097560975609756

In [46]:
a3 = np.array([[4,2,-3],[-2,3,1],[1,-1,2]])
b3 = np.array([10,-3,4])

In [47]:
x,y,z = np.linalg.solve(a3,b3)

In [48]:
x

2.853658536585366

In [49]:
y

0.6097560975609756

In [50]:
z

0.8780487804878049

### Conditional Selection with np.where()

In [52]:
A = np.random.randint(1,100,10)

In [53]:
A

array([29, 81, 52, 16,  8, 85, 25, 67, 14, 68])

In [57]:
gr50 = np.where(A>50)
gr50

(array([1, 2, 5, 7, 9], dtype=int64),)

In [69]:
B = np.array(A[A>50])

In [70]:
B

array([81, 52, 85, 67, 68])

In [71]:
np.mean(B)

70.6

In [73]:
A

array([29, 81, 52, 16,  8, 85, 25, 67, 14, 68])

In [74]:
B

array([81, 52, 85, 67, 68])

### Replace Values with np.where()

In [75]:
C = np.random.randint(-10,10,16).reshape((4,4))

In [76]:
C

array([[-6, -3, -8, -5],
       [-8,  2,  9, -6],
       [-5, -9, -6,  2],
       [ 5,  4,  8, -2]])

In [77]:
C = np.where(C<0, 0,C)
C

array([[0, 0, 0, 0],
       [0, 2, 9, 0],
       [0, 0, 0, 2],
       [5, 4, 8, 0]])